### ISSUE TITLE
Could you share the complete fairseq package? I can not run it

### ISSUE THREAD

**Issue by KpKqwq** [xssstory/SeqCo#3]

**Comment by xssstory** [comment]
Could you please show me some more details about the problems you encounter？

**Comment by KpKqwq** [comment]
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/user/anaconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/user/SeqCo-master/examples/__init__.py", line 8, in <module>
    import examples.noisychannel  # noqa
  File "/home/user/SeqCo-master/examples/noisychannel/__init__.py", line 6, in <module>
    from .rerank_options import *  # noqa
  File "/home/user/SeqCo-master/examples/noisychannel/rerank_options.py", line 6, in <module>
    from fairseq import options
  File "/home/user/SeqCo-master/fairseq/__init__.py", line 15, in <module>
    import fairseq.tasks  # noqa
  File "/home/user/SeqCo-master/fairseq/tasks/__init__.py", line 60, in <module>
    importlib.import_module('fairseq.tasks.' + task_name)
  File "/home/user/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/SeqCo-master/fairseq/tasks/back_summarization.py", line 27, in <module>
    from fairseq.data.bart_dataset import BartDataset
ModuleNotFoundError: No module named 'fairseq.data.bart_dataset'
I could not find the fairseq.data folder

**Comment by xssstory** [comment]
Thanks for your feedback! Now fairseq.data is added.

**Comment by KpKqwq** [comment]
thank you very much!
