### ISSUE TITLE
AssertionError while training model

### ISSUE THREAD

**Issue by LieuMai** [xssstory/SeqCo#5]
1. When I run sh seqco_scripts/train_cnndm.sh command I get an error say cuda out of memory. I find related issue and people suggest to reduce the batch size. Can someone tell me how to reduce batch size?
2. I follow a solution and try adding these parameter in train_cnndm.sh :   --memory-efficient-fp16 \ --optimizer adafactor \ but it show me the error below.

nvidia-smi:

```
Mon Oct 17 23:30:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P0    N/A /  N/A |      0MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
Full error log: 
```
Traceback (most recent call last):
  File "train.py", line 344, in <module>
    cli_main()
  File "train.py", line 340, in cli_main
    main(args)
  File "train.py", line 93, in main
    train(args, trainer, task, epoch_itr)
  File "train.py", line 134, in train
    log_output = trainer.train_step(samples)
  File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 339, in train_step
    loss, sample_size, logging_output = self.task.train_step(
  File "/home/lieumai/TextSum/SeqCo/fairseq/tasks/finetune_summarization.py", line 984, in train_step
    real_sample_list, action_log_probs = self.dataset('train').datasets[sample_key].real_collater(sample[sample_key], self.pg_ratio>0.0)
  File "/home/lieumai/TextSum/SeqCo/fairseq/data/backsum_dataset.py", line 211, in real_collater
    assert self.cur_accumulate <= self.accumulate_step
AssertionError
```
OOM error log:
```
| model backsum_transformer_bart_large, criterion LabelSmoothedCrossEntropyCriterion | num. model params: 630956032 (num. trained: 418883584) | training on 1 GPUs | max tokens per GPU = None and max sentences per GPU = 2 | no existing checkpoint found /data/msra/sum_data//cnndm_bart/bart.large/model.pt | loading train data for epoch 0 | loaded 1093 examples from: data/cnn_dm-bin/train.article-summary.article | loaded 1093 examples from: data/cnn_dm-bin/train.article-summary.summary | parallel-data/cnn_dm-bin train 1093 examples | loaded 1093 examples from: data/cnn_dm-bin/train.article-summary.article | backtranslate-article: data/cnn_dm-bin train 1093 examples | WARNING: your device does NOT support faster training with --fp16, please switch to FP32 which is likely to be faster Traceback (most recent call last):   File "train.py", line 344, in <module>
    cli_main()   File "train.py", line 340, in cli_main
    main(args)   File "train.py", line 77, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)   File "/home/lieumai/TextSum/SeqCo/fairseq/checkpoint_utils.py", line 143, in load_checkpoint
    trainer.lr_step(epoch_itr.epoch)   File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 600, in lr_step
    self.lr_scheduler.step(epoch, val_loss)   File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 121, in lr_scheduler
    self._build_optimizer()  # this will initialize self._lr_scheduler   File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 143, in
_build_optimizer
    self._optimizer = optim.FP16Optimizer.build_optimizer(self.args, params)   File "/home/lieumai/TextSum/SeqCo/fairseq/optim/fp16_optimizer.py", line 207, in build_optimizer
    fp32_params = cls.build_fp32_params(params)   File "/home/lieumai/TextSum/SeqCo/fairseq/optim/fp16_optimizer.py", line 67, in build_fp32_params
    fp32_params = params[0].new(0).float().new(total_param_size) RuntimeError: CUDA out of memory. Tried to allocate 1.56 GiB (GPU 0;
1.96 GiB total capacity; 1.18 GiB already allocated; 303.56 MiB free; 1.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF 
```

**Comment by hanyi-zou** [comment]
> 1. When I run sh seqco_scripts/train_cnndm.sh command I get an error say cuda out of memory. I find related issue and people suggest to reduce the batch size. Can someone tell me how to reduce batch size?
> 2. I follow a solution and try adding these parameter in train_cnndm.sh :   --memory-efficient-fp16 \ --optimizer adafactor \ but it show me the error below.
> 
> nvidia-smi:
> 
> ```
> Mon Oct 17 23:30:15 2022       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
> | N/A   51C    P0    N/A /  N/A |      0MiB /  2048MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```
> 
> Full error log:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 344, in <module>
>     cli_main()
>   File "train.py", line 340, in cli_main
>     main(args)
>   File "train.py", line 93, in main
>     train(args, trainer, task, epoch_itr)
>   File "train.py", line 134, in train
>     log_output = trainer.train_step(samples)
>   File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 339, in train_step
>     loss, sample_size, logging_output = self.task.train_step(
>   File "/home/lieumai/TextSum/SeqCo/fairseq/tasks/finetune_summarization.py", line 984, in train_step
>     real_sample_list, action_log_probs = self.dataset('train').datasets[sample_key].real_collater(sample[sample_key], self.pg_ratio>0.0)
>   File "/home/lieumai/TextSum/SeqCo/fairseq/data/backsum_dataset.py", line 211, in real_collater
>     assert self.cur_accumulate <= self.accumulate_step
> AssertionError
> ```
> 
> OOM error log:
> 
> ```
> | model backsum_transformer_bart_large, criterion LabelSmoothedCrossEntropyCriterion | num. model params: 630956032 (num. trained: 418883584) | training on 1 GPUs | max tokens per GPU = None and max sentences per GPU = 2 | no existing checkpoint found /data/msra/sum_data//cnndm_bart/bart.large/model.pt | loading train data for epoch 0 | loaded 1093 examples from: data/cnn_dm-bin/train.article-summary.article | loaded 1093 examples from: data/cnn_dm-bin/train.article-summary.summary | parallel-data/cnn_dm-bin train 1093 examples | loaded 1093 examples from: data/cnn_dm-bin/train.article-summary.article | backtranslate-article: data/cnn_dm-bin train 1093 examples | WARNING: your device does NOT support faster training with --fp16, please switch to FP32 which is likely to be faster Traceback (most recent call last):   File "train.py", line 344, in <module>
>     cli_main()   File "train.py", line 340, in cli_main
>     main(args)   File "train.py", line 77, in main
>     extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)   File "/home/lieumai/TextSum/SeqCo/fairseq/checkpoint_utils.py", line 143, in load_checkpoint
>     trainer.lr_step(epoch_itr.epoch)   File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 600, in lr_step
>     self.lr_scheduler.step(epoch, val_loss)   File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 121, in lr_scheduler
>     self._build_optimizer()  # this will initialize self._lr_scheduler   File "/home/lieumai/TextSum/SeqCo/fairseq/trainer.py", line 143, in
> _build_optimizer
>     self._optimizer = optim.FP16Optimizer.build_optimizer(self.args, params)   File "/home/lieumai/TextSum/SeqCo/fairseq/optim/fp16_optimizer.py", line 207, in build_optimizer
>     fp32_params = cls.build_fp32_params(params)   File "/home/lieumai/TextSum/SeqCo/fairseq/optim/fp16_optimizer.py", line 67, in build_fp32_params
>     fp32_params = params[0].new(0).float().new(total_param_size) RuntimeError: CUDA out of memory. Tried to allocate 1.56 GiB (GPU 0;
> 1.96 GiB total capacity; 1.18 GiB already allocated; 303.56 MiB free; 1.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF 
> ```

it's seems like your GPU memory is too small
